from pathlib import Path

root=Path('Ledger-Pro-PK-Vercel-v2/app')
app=root/'ledger-app.tsx'
text=app.read_text()

def rep(old,new,label):
    global text
    if old not in text:
        raise SystemExit(f'missing replacement: {label}')
    text=text.replace(old,new,1)

rep('import ProProductModal from "./pro-product-modal";','import ProProductModal from "./pro-product-modal";\nimport PartyLedgerModal from "./party-ledger-modal";','import ledger modal')
rep('type Modal="contact"|"product"|"transaction"|"adjustment"|null;','type Modal="contact"|"product"|"transaction"|"adjustment"|"ledger"|null;','modal type')
rep('  const [modal,setModal]=useState<Modal>(null),[editing,setEditing]=useState<Contact|Product|Tx|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");',
'''  const [modal,setModal]=useState<Modal>(null),[editing,setEditing]=useState<Contact|Product|Tx|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const [txPreset,setTxPreset]=useState<Tx["type"]|null>(null),[txPresetContactId,setTxPresetContactId]=useState(""),[ledgerContact,setLedgerContact]=useState<Contact|null>(null);''','modal state')
rep('  function open(kind:Modal,item:Contact|Product|Tx|null=null){setEditing(item);setModal(kind)}\n  function close(){setModal(null);setEditing(null)}',
'''  function open(kind:Modal,item:Contact|Product|Tx|null=null){setEditing(item);setModal(kind)}
  function openTransaction(type:Tx["type"],contactId=""){setTxPreset(type);setTxPresetContactId(contactId);setEditing(null);setModal("transaction")}
  function openLedger(contact:Contact){setLedgerContact(contact);setModal("ledger")}
  function close(){setModal(null);setEditing(null);setLedgerContact(null);setTxPresetContactId("")}''','open helpers')
rep('  function newRecord(){if(section==="contacts")open("contact");else if(section==="stock")open("product");else if(!["reports","settings"].includes(section))open("transaction")}\n  const defaultTxType:Tx["type"]=section==="purchases"?"purchase":section==="cash"?"payment_in":"sale";',
'''  function newRecord(){if(section==="contacts")open("contact");else if(section==="stock")open("product");else if(!["reports","settings","sales","purchases"].includes(section))openTransaction(section==="cash"?"payment_in":"sale")}
  const defaultTxType:Tx["type"]=txPreset||(section==="purchases"?"purchase":section==="cash"?"payment_in":"sale");''','new record')
rep('  const showAdd=section!=="reports"&&section!=="settings";', '  const showAdd=!(["reports","settings","sales","purchases"] as Section[]).includes(section);','show add')
rep('{section==="contacts"&&<Contacts rows={filteredContacts} transactions={transactions} open={open} archive={archiveContact} restore={restoreContact} canManage={canManage}/>} ',
'{section==="contacts"&&<Contacts rows={filteredContacts} transactions={transactions} open={open} openLedger={openLedger} openPayment={(c)=>openTransaction(c.type==="customer"?"payment_in":"payment_out",c.id)} archive={archiveContact} restore={restoreContact} canManage={canManage}/>} ','contacts render')
rep('{section==="sales"&&<Transactions title="Farokht aur wasooli" rows={filteredTx.filter(x=>x.type==="sale"||x.type==="payment_in")} contacts={contacts} products={products} open={open} voidTx={voidTransaction} canManage={canManage}/>} ',
'{section==="sales"&&<><SectionActions mode="sales" openTx={openTransaction} goKhatay={()=>goto("contacts")}/><Transactions title="Farokht aur wasooli" rows={filteredTx.filter(x=>x.type==="sale"||x.type==="payment_in")} contacts={contacts} products={products} open={open} voidTx={voidTransaction} canManage={canManage}/></>} ','sales actions')
rep('{section==="purchases"&&<Transactions title="Khareedari aur supplier adayegi" rows={filteredTx.filter(x=>x.type==="purchase"||x.type==="payment_out")} contacts={contacts} products={products} open={open} voidTx={voidTransaction} canManage={canManage}/>} ',
'{section==="purchases"&&<><SectionActions mode="purchases" openTx={openTransaction} goKhatay={()=>goto("contacts")}/><Transactions title="Khareedari aur supplier adayegi" rows={filteredTx.filter(x=>x.type==="purchase"||x.type==="payment_out")} contacts={contacts} products={products} open={open} voidTx={voidTransaction} canManage={canManage}/></>} ','purchase actions')
rep('{modal==="transaction"&&<ProTransactionModal businessId={businessId} item={editing as Tx|null} defaultType={defaultTxType} contacts={contacts} products={products} busy={busy} setBusy={setBusy} close={close} done={()=>{close();toast("Transaction, calculation aur stock update ho gaye");void reloadTransactionsAndProducts()}}/>}',
'{modal==="transaction"&&<ProTransactionModal businessId={businessId} item={editing as Tx|null} defaultType={defaultTxType} presetContactId={txPresetContactId} contacts={contacts} products={products} transactions={transactions} busy={busy} setBusy={setBusy} close={close} contactCreated={()=>void reloadContacts()} done={()=>{close();toast("Transaction, calculation aur stock update ho gaye");void reloadTransactionsAndProducts();void reloadContacts()}}/>}\n    {modal==="ledger"&&ledgerContact&&<PartyLedgerModal contact={ledgerContact} transactions={transactions} products={products} close={close} recordPayment={(c)=>{setLedgerContact(null);openTransaction(c.type==="customer"?"payment_in":"payment_out",c.id)}}/>}','transaction and ledger modal')
old_contacts='''function Contacts({rows,transactions,open,archive,restore,canManage}:{rows:Contact[];transactions:Tx[];open:(m:Modal,i?:Contact)=>void;archive:(id:string,l:string)=>void;restore:(id:string)=>void;canManage:boolean}){const active=rows.filter(x=>x.is_active),archived=rows.filter(x=>!x.is_active);const card=(x:Contact,arch=false)=>{const balance=contactBalance(x,transactions);return <div className="contactCard" key={x.id}><i>{x.name.split(" ").map(s=>s[0]).slice(0,2).join("")}</i><span><small>{x.type==="customer"?"Customer":"Supplier"}{arch?" · Archived":""}</small><b>{x.name}</b><em>{x.phone||x.email||"No contact"}</em></span><section><small>{balance>=0?(x.type==="customer"?"Wasooli baqi":"Adayegi baqi"):"Advance"}</small><b>{money(Math.abs(balance))}</b><small>Opening: {money(x.opening_balance)}</small>{canManage&&<div>{!arch&&<button onClick={()=>open("contact",x)}>Edit</button>}{arch?<button onClick={()=>restore(x.id)}>Restore</button>:<button className="danger" onClick={()=>archive(x.id,x.name)}>Archive</button>}</div>}</section></div>};return <article className="panel full"><PanelHead title="Customer aur supplier khatay" sub="Current balance auto ledger se calculate hota hai"/><div className="cards">{active.map(x=>card(x))}{!active.length&&<Empty text="Koi active khata nahi mila"/>}</div>{archived.length>0&&<details className="archiveGroup"><summary>Archived khatay ({archived.length})</summary><div className="cards">{archived.map(x=>card(x,true))}</div></details>}</article>}'''
new_contacts='''function Contacts({rows,transactions,open,openLedger,openPayment,archive,restore,canManage}:{rows:Contact[];transactions:Tx[];open:(m:Modal,i?:Contact)=>void;openLedger:(c:Contact)=>void;openPayment:(c:Contact)=>void;archive:(id:string,l:string)=>void;restore:(id:string)=>void;canManage:boolean}){const active=rows.filter(x=>x.is_active),archived=rows.filter(x=>!x.is_active);const card=(x:Contact,arch=false)=>{const balance=contactBalance(x,transactions);return <div className="contactCard" key={x.id}><i>{x.name.split(" ").map(s=>s[0]).slice(0,2).join("")}</i><span><small>{x.type==="customer"?"Customer":"Supplier"}{arch?" · Archived":""}</small><b>{x.name}</b><em>{x.phone||x.email||"No contact"}</em></span><section><small>{balance>=0?(x.type==="customer"?"Wasooli baqi":"Adayegi baqi"):"Advance"}</small><b>{money(Math.abs(balance))}</b><small>Opening: {money(x.opening_balance)}</small><div className="contactActions"><button onClick={()=>openLedger(x)}>Khata / Statement</button>{!arch&&<button onClick={()=>openPayment(x)}>{x.type==="customer"?"Wasooli":"Adayegi"}</button>}{canManage&&<>{!arch&&<button onClick={()=>open("contact",x)}>Edit</button>}{arch?<button onClick={()=>restore(x.id)}>Restore</button>:<button className="danger" onClick={()=>archive(x.id,x.name)}>Archive</button>}</>}</div></section></div>};return <article className="panel full"><PanelHead title="Customer aur supplier khatay" sub="Har party ka separate running statement, due aur payment history"/><div className="cards">{active.map(x=>card(x))}{!active.length&&<Empty text="Koi active khata nahi mila"/>}</div>{archived.length>0&&<details className="archiveGroup"><summary>Archived khatay ({archived.length})</summary><div className="cards">{archived.map(x=>card(x,true))}</div></details>}</article>}'''
rep(old_contacts,new_contacts,'contacts component')
insert='''
function SectionActions({mode,openTx,goKhatay}:{mode:"sales"|"purchases";openTx:(type:Tx["type"],contactId?:string)=>void;goKhatay:()=>void}){const sales=mode==="sales";return <div className="sectionActions"><button className="primary" onClick={()=>openTx(sales?"sale":"purchase")}>{sales?"＋ Nayi Farokht":"＋ Nayi Khareedari"}</button><button className="ghost" onClick={()=>openTx(sales?"payment_in":"payment_out")}>{sales?"₨ Wasooli":"₨ Supplier Adayegi"}</button><button className="ghost" onClick={goKhatay}>{sales?"♙ Customer Khatay":"♙ Supplier Khatay"}</button></div>}

'''
rep('function Transactions({title,rows,contacts,products,open,voidTx,canManage}:',insert+'function Transactions({title,rows,contacts,products,open,voidTx,canManage}:','section actions component')
app.write_text(text)

modal=root/'pro-transaction-modal.tsx'
mt=modal.read_text()
if 'presetContactId' not in mt:
    mt=mt.replace('export default function ProTransactionModal({businessId,item,defaultType,contacts,products,transactions=[],busy,setBusy,close,done,contactCreated}:{businessId:string;item:Tx|null;defaultType:TxType;contacts:Contact[];products:Product[];transactions?:Tx[];busy:boolean;setBusy:(v:boolean)=>void;close:()=>void;done:()=>void;contactCreated?:()=>void}){',
'''export default function ProTransactionModal({businessId,item,defaultType,presetContactId="",contacts,products,transactions=[],busy,setBusy,close,done,contactCreated}:{businessId:string;item:Tx|null;defaultType:TxType;presetContactId?:string;contacts:Contact[];products:Product[];transactions?:Tx[];busy:boolean;setBusy:(v:boolean)=>void;close:()=>void;done:()=>void;contactCreated?:()=>void}){''')
    mt=mt.replace('const [contactId,setContactId]=useState(item?.contact_id||"");','const [contactId,setContactId]=useState(item?.contact_id||presetContactId||"");')
    mt=mt.replace('const [partyMode,setPartyMode]=useState<PartyMode>(item?.contact_id?"ledger":"cash");','const [partyMode,setPartyMode]=useState<PartyMode>(item?.contact_id||presetContactId?"ledger":"cash");')
modal.write_text(mt)

css=root/'pro-accounting.css'
ct=css.read_text()
append='''
.entryTypeTabs{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin:0 0 14px}.entryTypeTabs button{border:1px solid var(--line);background:var(--bg);color:var(--muted);border-radius:9px;padding:9px 6px;font-size:9px;font-weight:800}.entryTypeTabs button.active{border-color:var(--blue);background:#2563eb12;color:var(--blue)}
.partyModeBlock,.partyPicker,.ledgerExplain{border:1px solid var(--line);background:var(--bg);border-radius:12px;padding:12px;margin:0 0 14px}.partyModeTitle{display:block;color:var(--muted);font-size:9px;font-weight:800;margin-bottom:8px;text-transform:uppercase}.partyModeChoice{display:grid;grid-template-columns:1fr 1fr;gap:8px}.partyModeChoice button{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:10px;padding:11px;text-align:left}.partyModeChoice button.active{border-color:var(--blue);box-shadow:0 0 0 2px #2563eb16}.partyModeChoice b,.partyModeChoice small{display:block}.partyModeChoice b{font-size:10px}.partyModeChoice small{font-size:8px;color:var(--muted);margin-top:4px;line-height:1.4}
.partyPickerHead{display:flex;justify-content:space-between;align-items:center;margin-bottom:7px}.partyPickerHead b{font-size:10px}.partyPickerHead button{border:0;background:transparent;color:var(--blue);font-size:9px;font-weight:800}.partyPicker>select{width:100%;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:9px;padding:11px}.partyBalancePreview{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.partyBalancePreview span{border:1px solid var(--line);border-radius:9px;background:var(--panel);padding:9px}.partyBalancePreview small,.partyBalancePreview b{display:block}.partyBalancePreview small{font-size:8px;color:var(--muted)}.partyBalancePreview b{font-size:11px;margin-top:3px}.partyBalancePreview .advance,.ledgerAdvance{color:var(--green)}
.inlinePartyForm{display:grid;grid-template-columns:1fr 1fr auto;gap:7px;margin-top:10px}.inlinePartyForm input{margin:0!important;background:var(--panel)!important}.inlinePartyForm button{white-space:nowrap}.dueGuidance{border:1px solid #e4832055;background:#e4832010;color:var(--text);border-radius:10px;padding:10px 12px;margin:-2px 0 12px;font-size:9px;line-height:1.5}
.sectionActions{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px}.sectionActions button{min-height:38px}.contactActions{display:flex;justify-content:flex-end;gap:4px;flex-wrap:wrap;margin-top:8px}.contactActions button{margin-left:0!important}
.partyLedgerModal{width:min(980px,100%)}.ledgerContactMeta{font-size:9px;color:var(--muted);margin:3px 0 0}.ledgerSummary{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:stretch;margin-bottom:12px}.ledgerSummary>div{border:1px solid var(--line);background:var(--bg);border-radius:11px;padding:12px}.ledgerSummary small,.ledgerSummary b{display:block}.ledgerSummary small{font-size:8px;color:var(--muted);text-transform:uppercase}.ledgerSummary b{font-size:15px;margin-top:5px}.ledgerSummary .advance b{color:var(--green)}.ledgerSummary .due b{color:var(--orange)}.ledgerExplain{font-size:9px;color:var(--muted);line-height:1.5}.ledgerTable{max-height:50vh;border:1px solid var(--line);border-radius:11px;margin-bottom:14px}
.app.dark .modal input:disabled,.app.dark .modal input[readonly],.app.dark .modal select:disabled,.app.dark .settingsForm input:disabled,.app.dark .settingsForm textarea:disabled{-webkit-text-fill-color:var(--text)!important;color:var(--text)!important;opacity:1!important}.app.dark input[type="date"]::-webkit-calendar-picker-indicator{filter:invert(1)}.app.dark ::placeholder{color:#8290a7;opacity:1}
@media(max-width:760px){.entryTypeTabs{grid-template-columns:repeat(3,1fr)}.partyModeChoice{grid-template-columns:1fr}.inlinePartyForm{grid-template-columns:1fr}.partyBalancePreview{grid-template-columns:1fr 1fr}.ledgerSummary{grid-template-columns:1fr 1fr}.ledgerSummary>button{grid-column:1/-1}.sectionActions{display:grid;grid-template-columns:1fr 1fr}.sectionActions button:last-child{grid-column:1/-1}.partyLedgerModal{max-height:94dvh}}
'''
if '.entryTypeTabs{' not in ct:
    css.write_text(ct+'\n'+append)
