"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
import "./admin.css";

type Overview={users:number;businesses:number;active_businesses:number;suspended_businesses:number;transactions:number;new_users_30d:number};
type Business={id:string;name:string;status:"active"|"suspended"|"archived";plan:"free"|"pro"|"business";trial_ends_at:string|null;plan_expires_at:string|null;owner_email:string;members:number;transactions:number;created_at:string};

export default function AdminPage(){
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false);
  const [overview,setOverview]=useState<Overview|null>(null),[businesses,setBusinesses]=useState<Business[]>([]),[query,setQuery]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load();else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)void load();else{setAllowed(false);setLoading(false)}});return()=>subscription.unsubscribe()},[]);
  async function load(){setLoading(true);const [{data:isAdmin},{data:o,error:oe},{data:b,error:be}]=await Promise.all([supabase.rpc("platform_admin_me"),supabase.rpc("platform_admin_overview"),supabase.rpc("platform_admin_businesses")]);setAllowed(Boolean(isAdmin));if(oe||be)setMessage(oe?.message||be?.message||"");else{setOverview(o as Overview);setBusinesses((b||[]) as Business[])}setLoading(false)}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:String(f.get("email")||""),password:String(f.get("password")||"")});if(error){setMessage(error.message);setLoading(false)}}
  async function updateBusiness(item:Business,status:Business["status"],plan:Business["plan"]){setMessage("");const {error}=await supabase.rpc("platform_admin_update_business",{p_business_id:item.id,p_status:status,p_plan:plan,p_plan_expires_at:item.plan_expires_at});if(error)setMessage(error.message);else{setMessage(`${item.name} update ho gaya`);await load()}}
  if(loading)return <main className="adminState"><b>Ledger Pro Admin</b><p>Secure data load ho raha hai…</p></main>;
  if(!session)return <main className="adminLogin"><form onSubmit={login}><div className="adminLogo">LP</div><small>PLATFORM OWNER</small><h1>Super Admin Login</h1><p>Sirf Ledger Pro platform malik ke liye.</p><label>Email<input type="email" name="email" required/></label><label>Password<input type="password" name="password" required/></label>{message&&<em>{message}</em>}<button>Secure Login</button><a href="/">Customer app par jayein</a></form></main>;
  if(!allowed)return <main className="adminState"><b>Access denied</b><p>Ye account Platform Super Admin nahi hai.</p><button onClick={()=>supabase.auth.signOut()}>Logout</button></main>;
  const filtered=businesses.filter(b=>`${b.name} ${b.owner_email} ${b.plan} ${b.status}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="adminApp"><aside><div className="adminBrand"><b>LP</b><span>Ledger Pro<small>SUPER ADMIN</small></span></div><nav><button className="active">▦ Dashboard</button><button>♙ Businesses</button><button>⌁ Plans & Usage</button></nav><footer><small>{session.user.email}</small><button onClick={()=>supabase.auth.signOut()}>Logout</button></footer></aside><section><header><div><small>PLATFORM CONTROL</small><h1>Owner Dashboard</h1></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business ya email search…"/></header>{message&&<div className="adminNotice">{message}</div>}{overview&&<div className="adminStats"><Stat label="Total Users" value={overview.users}/><Stat label="Businesses" value={overview.businesses}/><Stat label="Active" value={overview.active_businesses}/><Stat label="Suspended" value={overview.suspended_businesses}/><Stat label="Transactions" value={overview.transactions}/><Stat label="New Users (30d)" value={overview.new_users_30d}/></div>}<article><div className="adminHead"><div><h2>Businesses Management</h2><p>Plans, access aur customer activity.</p></div><button onClick={load}>Refresh</button></div><div className="adminTable"><table><thead><tr><th>Business</th><th>Owner</th><th>Usage</th><th>Plan</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td data-label="Business"><b>{b.name}</b><small>{new Date(b.created_at).toLocaleDateString("en-PK")}</small></td><td data-label="Owner">{b.owner_email}</td><td data-label="Usage">{b.members} members · {b.transactions} tx</td><td data-label="Plan"><select value={b.plan} onChange={e=>updateBusiness(b,b.status,e.target.value as Business["plan"])}><option value="free">Free</option><option value="pro">Pro</option><option value="business">Business</option></select></td><td data-label="Status"><span className={b.status}>{b.status}</span></td><td data-label="Action"><button className={b.status==="active"?"suspend":"activate"} onClick={()=>updateBusiness(b,b.status==="active"?"suspended":"active",b.plan)}>{b.status==="active"?"Suspend":"Activate"}</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="noRows">Koi business nahi mila.</p>}</div></article></section></main>
}
function Stat({label,value}:{label:string;value:number}){return <article><small>{label}</small><b>{value.toLocaleString()}</b></article>}
