"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
import "./admin.css";
import "./admin-fixes.css";

type AdminSection="dashboard"|"businesses"|"plans";
type Overview={users:number;businesses:number;active_businesses:number;suspended_businesses:number;transactions:number;new_users_30d:number};
type Business={id:string;name:string;status:"active"|"suspended"|"archived";plan:"free"|"pro"|"business";trial_ends_at:string|null;plan_expires_at:string|null;owner_email:string;members:number;transactions:number;created_at:string};
type PlanUsage={id:string;name:string;plan:string;status:string;max_members:number;max_monthly_transactions:number;members:number;monthly_transactions:number;plan_expires_at:string|null};

export default function AdminPage(){
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false);
  const [section,setSection]=useState<AdminSection>("dashboard"),[overview,setOverview]=useState<Overview|null>(null),[businesses,setBusinesses]=useState<Business[]>([]),[usage,setUsage]=useState<PlanUsage[]>([]),[query,setQuery]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load();else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)void load();else{setAllowed(false);setLoading(false)}});return()=>subscription.unsubscribe()},[]);
  async function load(){setLoading(true);setMessage("");const [{data:isAdmin,error:ae},{data:o,error:oe},{data:b,error:be},{data:u,error:ue}]=await Promise.all([supabase.rpc("platform_admin_me"),supabase.rpc("platform_admin_overview"),supabase.rpc("platform_admin_businesses"),supabase.rpc("platform_admin_plan_usage")]);setAllowed(Boolean(isAdmin));const err=ae||oe||be||ue;if(err)setMessage(err.message);else{setOverview(o as Overview);setBusinesses((b||[]) as Business[]);setUsage((u||[]) as PlanUsage[])}setLoading(false)}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:String(f.get("email")||""),password:String(f.get("password")||"")});if(error){setMessage(error.message);setLoading(false)}}
  async function updateBusiness(item:Business,status:Business["status"],plan:Business["plan"]){setMessage("");const {error}=await supabase.rpc("platform_admin_update_business",{p_business_id:item.id,p_status:status,p_plan:plan,p_plan_expires_at:item.plan_expires_at});if(error)setMessage(error.message);else{setMessage(`${item.name} update ho gaya`);await load()}}
  if(loading)return <main className="adminState"><b>Ledger Pro Admin</b><p>Secure data load ho raha hai…</p></main>;
  if(!session)return <main className="adminLogin"><form onSubmit={login}><div className="adminLogo">LP</div><small>PLATFORM OWNER</small><h1>Super Admin Login</h1><p>Sirf Ledger Pro platform malik ke liye.</p><label>Email<input type="email" name="email" required/></label><label>Password<input type="password" name="password" required/></label>{message&&<em>{message}</em>}<button>Secure Login</button><a href="/">Customer app par jayein</a></form></main>;
  if(!allowed)return <main className="adminState"><b>Access denied</b><p>Ye account Platform Super Admin nahi hai.</p><button onClick={()=>supabase.auth.signOut()}>Logout</button></main>;
  const filtered=businesses.filter(b=>`${b.name} ${b.owner_email} ${b.plan} ${b.status}`.toLowerCase().includes(query.toLowerCase()));
  const filteredUsage=usage.filter(b=>`${b.name} ${b.plan} ${b.status}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="adminApp"><aside><div className="adminBrand"><b>LP</b><span>Ledger Pro<small>SUPER ADMIN</small></span></div><nav><button className={section==="dashboard"?"active":""} onClick={()=>setSection("dashboard")}>▦ Dashboard</button><button className={section==="businesses"?"active":""} onClick={()=>setSection("businesses")}>♙ Businesses</button><button className={section==="plans"?"active":""} onClick={()=>setSection("plans")}>⌁ Plans & Usage</button></nav><footer><small>{session.user.email}</small><button onClick={()=>window.location.assign("/")}>← Business App</button><button onClick={()=>supabase.auth.signOut()}>Logout</button></footer></aside><section><header><div><small>PLATFORM CONTROL</small><h1>{section==="dashboard"?"Owner Dashboard":section==="businesses"?"Businesses":"Plans & Usage"}</h1></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business, email ya plan search…"/></header>{message&&<div className="adminNotice">{message}</div>}{section==="dashboard"&&<Dashboard overview={overview} businesses={businesses} goBusinesses={()=>setSection("businesses")} goPlans={()=>setSection("plans")} refresh={load}/>} {section==="businesses"&&<BusinessesTable rows={filtered} updateBusiness={updateBusiness} refresh={load}/>} {section==="plans"&&<PlanUsageTable rows={filteredUsage}/>}</section></main>
}
function Dashboard({overview,businesses,goBusinesses,goPlans,refresh}:{overview:Overview|null;businesses:Business[];goBusinesses:()=>void;goPlans:()=>void;refresh:()=>void}){return <>{overview&&<div className="adminStats"><Stat label="Total Users" value={overview.users}/><Stat label="Businesses" value={overview.businesses}/><Stat label="Active" value={overview.active_businesses}/><Stat label="Suspended" value={overview.suspended_businesses}/><Stat label="Transactions" value={overview.transactions}/><Stat label="New Users (30d)" value={overview.new_users_30d}/></div>}<div className="adminQuick"><button onClick={goBusinesses}><b>Businesses manage karein</b><small>Plan, status aur owner usage</small></button><button onClick={goPlans}><b>Plans & Usage dekhein</b><small>Monthly limits aur consumption</small></button><button onClick={refresh}><b>Data refresh karein</b><small>Latest platform numbers</small></button></div><article><div className="adminHead"><div><h2>Recent businesses</h2><p>Latest registered businesses.</p></div><button onClick={goBusinesses}>View all</button></div><div className="adminTable"><table><thead><tr><th>Business</th><th>Owner</th><th>Plan</th><th>Status</th></tr></thead><tbody>{businesses.slice(0,8).map(b=><tr key={b.id}><td data-label="Business"><b>{b.name}</b><small>{new Date(b.created_at).toLocaleDateString("en-PK")}</small></td><td data-label="Owner">{b.owner_email}</td><td data-label="Plan">{b.plan}</td><td data-label="Status"><span className={b.status}>{b.status}</span></td></tr>)}</tbody></table></div></article></>}
function BusinessesTable({rows,updateBusiness,refresh}:{rows:Business[];updateBusiness:(item:Business,status:Business["status"],plan:Business["plan"])=>void;refresh:()=>void}){return <article><div className="adminHead"><div><h2>Businesses Management</h2><p>Plans, access aur customer activity.</p></div><button onClick={refresh}>Refresh</button></div><div className="adminTable"><table><thead><tr><th>Business</th><th>Owner</th><th>Usage</th><th>Plan</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td data-label="Business"><b>{b.name}</b><small>{new Date(b.created_at).toLocaleDateString("en-PK")}</small></td><td data-label="Owner">{b.owner_email}</td><td data-label="Usage">{b.members} members · {b.transactions} tx</td><td data-label="Plan"><select value={b.plan} onChange={e=>void updateBusiness(b,b.status,e.target.value as Business["plan"])}><option value="free">Free</option><option value="pro">Pro</option><option value="business">Business</option></select></td><td data-label="Status"><span className={b.status}>{b.status}</span></td><td data-label="Action"><button className={b.status==="active"?"suspend":"activate"} onClick={()=>void updateBusiness(b,b.status==="active"?"suspended":"active",b.plan)}>{b.status==="active"?"Suspend":"Activate"}</button></td></tr>)}</tbody></table>{!rows.length&&<p className="noRows">Koi business nahi mila.</p>}</div></article>}
function PlanUsageTable({rows}:{rows:PlanUsage[]}){return <article><div className="adminHead"><div><h2>Monthly plan usage</h2><p>Limits database par enforce hoti hain.</p></div></div><div className="adminTable"><table><thead><tr><th>Business</th><th>Plan</th><th>Members</th><th>Monthly Tx</th><th>Member Use</th><th>Tx Use</th><th>Expiry</th></tr></thead><tbody>{rows.map(b=>{const memberPct=Math.min(100,Math.round((Number(b.members)/Math.max(1,b.max_members))*100));const txPct=Math.min(100,Math.round((Number(b.monthly_transactions)/Math.max(1,b.max_monthly_transactions))*100));return <tr key={b.id}><td data-label="Business"><b>{b.name}</b><small>{b.status}</small></td><td data-label="Plan">{b.plan}</td><td data-label="Members">{b.members} / {b.max_members}</td><td data-label="Monthly Tx">{b.monthly_transactions} / {b.max_monthly_transactions}</td><td data-label="Member Use"><Meter value={memberPct}/></td><td data-label="Tx Use"><Meter value={txPct}/></td><td data-label="Expiry">{b.plan_expires_at?new Date(b.plan_expires_at).toLocaleDateString("en-PK"):"No expiry"}</td></tr>})}</tbody></table>{!rows.length&&<p className="noRows">Koi usage record nahi mila.</p>}</div></article>}
function Meter({value}:{value:number}){return <div className="usageMeter"><span style={{width:`${value}%`}}/><small>{value}%</small></div>}
function Stat({label,value}:{label:string;value:number}){return <article><small>{label}</small><b>{Number(value||0).toLocaleString()}</b></article>}
